;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
         query-replace
         ))

(setq mc/cmds-to-run-once
      '(
         c-electric-paren
         c-electric-semi&comma
         c-electric-slash
         c-electric-star
         cua-scroll-up
         eval-print-last-sexp
         indent-for-tab-command
         mode-line-minor-mode-help
         mouse-set-region
         overwrite-mode
         rectangle-left-char
         rectangle-next-line
         rectangle-previous-line
         rectangle-right-char
         scroll-bar-toolkit-horizontal-scroll
         toggle-input-method
         undefined
         widget-button-click
         ))
