(deftheme local-faces
  "Created 2018-06-18.")

(custom-theme-set-faces 
  'local-faces

  '(default ((t (:inherit nil :stipple nil :background "#2d3743" :foreground "#c1c1c0" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 120 :width normal :foundry "PfEd" :family "DejaVu Sans Mono"))))
  '(company-scrollbar-bg ((t (:background "light gray"))))
  '(company-scrollbar-fg ((t (:background "snow4"))))
  '(company-template-field ((t (:background "#34ef9a" :foreground "#414141"))))
  '(company-tooltip ((t (:background "#54efff" :foreground "#3a3a39"))))
  '(company-tooltip-common ((t (:foreground "#0000bb" :weight bold))))
  '(company-tooltip-selection ((t (:background "#bfbfff"))))
  '(cursor ((t (:background "azure1"))))
  '(dired-directory ((t (:inherit font-lock-type-face :foreground "#00bfff" :underline t :weight semi-bold :height 1.03))))
  '(dired-flagged ((t (:foreground "pink2" :box (:line-width -1 :color "gray35" :style pressed-button) :strike-through "pink3" :slant italic))))
  '(dired-header ((t (:inherit dired-directory :foreground "#2abee9" :box (:line-width 1 :color "grey45" :style released-button) :underline t :height 1.8))))
  '(dired-mark ((t (:inherit dired-flagged :foreground "indianred1" :box (:line-width 1 :color "darkorange3" :style released-button) :strike-through nil :slant normal :weight bold))))
  '(dired-symlink ((t (:foreground "#208acb" :slant italic))))
  '(font-lock-builtin-face ((t (:foreground "#23ffef" :weight extra-bold))))
  '(font-lock-comment-delimiter-face ((t (:inherit font-lock-comment-face))))
  '(font-lock-comment-face ((t (:foreground "#74af68" :slant italic))))
  '(font-lock-doc-face ((t (:inherit font-lock-string-face :slant italic))))
  '(font-lock-keyword-face ((t (:foreground "#f68627" :weight bold))))
  '(font-lock-preprocessor-face ((t (:foreground "#f68627" :slant italic))))
  '(font-lock-regexp-grouping-construct ((t (:inherit bold))))
  '(font-lock-string-face ((t (:foreground "#5bbb35" :weight bold))))
  '(font-lock-type-face ((t (:foreground "#23afd8" :weight semi-bold))))
  '(font-lock-variable-name-face ((t (:foreground "#dbdb95"))))
  '(fringe ((t (:background "#323c47"))))
  '(highlight ((t (:inherit nil :background "#2f3f4f"))))
  '(hl-line ((t (:background "#2f3f4f"))))
  '(lazy-highlight ((t (:background "#335f86"))))
  '(linum ((t (:inherit (default hl-line) :stipple nil :foreground "#8b8682" :strike-through nil :overline nil :slant normal :height 110 :width condensed))))
  '(mc/cursor-face ((t (:background "cyan4" :inverse-video nil :box (:line-width 1 :color "#55cc66" :style released-button)))))
  '(mode-line ((t (:background "#212931" :foreground "#eeeeec" :box (:line-width 1 :color "#264969" :style released-button) :overline "dark violet"))))
  '(mode-line-inactive ((t (:inherit mode-line :background "grey30" :foreground "grey80" :box (:line-width 1 :color "grey40" :style released-button) :overline nil :weight light))))
  '(region ((t (:inherit hl-line :background "#3d7d5e"))))
  '(scroll-bar ((t nil)))
  '(secondary-selection ((t (:background "SkyBlue4"))))
  '(shadow ((t (:foreground "grey64"))))
  '(show-paren-match ((t (:background "#3f5a90" :inverse-video nil :box (:line-width -1 :color "deep sky blue") :underline (:color "deep sky blue" :style wave) :weight bold))))
  '(show-paren-mismatch ((t (:box (:line-width -1 :color "magenta") :underline (:color "magenta" :style wave) :weight bold))))
  '(warning ((t (:foreground "VioletRed1" :weight bold))))
  '(window-divider ((t (:foreground "dark cyan"))))
  '(window-divider-first-pixel ((t (:foreground "dark cyan"))))
  '(window-divider-last-pixel ((t (:foreground "light sea green"))))
 )

(provide-theme 'local-faces)
