(deftheme local-faces
  "Created 2018-06-18.")

(custom-theme-set-faces
  'local-faces

  '(ac-candidate-face ((t (:inherit cider-result-overlay-face))))
  '(ahs-definition-face ((t (:background "#3f4850" :overline "#00aeae" :underline "#00aeae"))))
  '(ahs-edit-mode-face ((t (:underline (:color "Coral3" :style wave) :weight extra-bold))))
  '(ahs-face ((t (:inherit hl-line :background "#2f3f4f" :overline "#a09475" :underline "#a09475"))))
  '(ahs-plugin-defalt-face ((t (:inherit ahs-face))))
  '(button ((t (:inherit link))))
  '(cargo-process--warning-face ((t (:inherit (warning shadow)))))
  '(cider-reader-conditional-face ((t (:inherit font-lock-preprocessor-face))))
  '(cider-repl-prompt-face ((t (:inherit font-lock-keyword-face))))
  '(cider-repl-result-face ((t (:slant italic))))
  '(cider-repl-stderr-face ((t (:inherit warning))))
  '(cider-repl-stdout-face ((t (:inherit default))))
  '(cider-result-overlay-face ((t (:inherit shadow :box (:line-width -1 :color "gray13"))))) 
  '(cider-warning-highlight-face ((t (:inherit font-lock-warning-face))))
  '(clojure-character-face ((t (:foreground "#5bbb35" :weight normal :width normal))))
  '(clojure-keyword-face ((t (:inherit font-lock-constant-face))))
  '(comint-highlight-input ((t nil)))
  '(company-scrollbar-bg ((t (:background "light gray"))))
  '(company-scrollbar-fg ((t (:background "snow4"))))
  '(company-template-field ((t (:background "#305e5b" :foreground "#262e1b"))))
  '(company-tooltip-common ((t (:foreground "#0000bb" :weight bold))))
  '(company-tooltip-selection ((t (:background "#bfbfff"))))
  '(company-tooltip ((t (:background "#407b7b" :foreground "#222a19"))))
  '(completions-common-part ((t (:inherit (shadow highlight) :underline "#636865" :slant italic :weight light))))
  '(completions-first-difference ((t (:inherit (bold hl-line) :underline (:color "#636865" :style wave) :slant italic))))
  '(cursor ((t (:background "#bdd8e2"))))
  '(custom-button ((t (:background "lightgrey" :foreground "black" :box (:line-width 2 :style released-button)))))
  '(custom-button-unraised ((t (:inherit (link bold)))))
  '(default ((t (:inherit nil :stipple nil :background "#2d3743" :foreground "#d6cfc8" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 122 :width semi-expanded :family "DejaVu Sans Mono"))))
  '(dired-directory ((t (:inherit font-lock-type-face :foreground "#00bfff" :underline t :weight semi-bold :height 1.03))))
  '(dired-flagged ((t (:foreground "pink2" :box (:line-width -1 :color "gray35" :style pressed-button) :strike-through "pink3" :slant italic))))
  '(dired-header ((t (:inherit dired-directory :foreground "#2abee9" :box (:line-width 1 :color "grey45" :style released-button) :underline t :height 1.0))))
  '(dired-mark ((t (:inherit dired-flagged :foreground "indianred1" :box (:line-width 1 :color "darkorange3" :style released-button) :strike-through nil :slant normal :weight bold))))
  '(dired-symlink ((t (:foreground "#208acb" :slant italic))))
  '(eldoc-highlight-function-argument ((t (:inherit bold :underline (:color "#888a8e" :style wave)))))
  '(error ((t (:background "#2d3803" :foreground "#ff2520" :underline t :weight normal))))
  '(fixed-pitch-serif ((t (:family "DejaVu Sans Serif"))))
  '(fixed-pitch ((t (:family "DejaVu Sans Mono Book"))))
  '(flycheck-color-mode-line-error-face ((t (:inherit mode-line :overline "#ff2520"))))
  '(flycheck-color-mode-line-info-face ((t (:inherit mode-line :overline "#b8860b"))))
  '(flycheck-color-mode-line-running-face ((t (:inherit mode-line :overline "MediumPurple1"))))
  '(flycheck-color-mode-line-success-face ((t (:inherit mode-line))))
  '(flycheck-color-mode-line-warning-face ((t (:inherit mode-line :overline "#ee8d32"))))
  '(flycheck-error-list-checker-name ((t (:inherit (font-lock-function-name-face highlight)))))
  '(flycheck-error-list-column-number ((t (:inherit (font-lock-constant-face highlight)))))
  '(flycheck-error-list-error ((t (:inherit (highlight error) :underline nil :weight normal))))
  '(flycheck-error-list-filename ((t (:inherit (font-lock-variable-name-face highlight)))))
  '(flycheck-error-list-highlight ((t (:inherit highlight :underline (:color "DarkOrange3" :style wave)))))
  '(flycheck-error-list-id ((t (:inherit (font-lock-type-face highlight)))))
  '(flycheck-error-list-info ((t (:inherit (success highlight)))))
  '(flycheck-error-list-line-number ((t (:inherit (font-lock-constant-face highlight)))))
  '(flycheck-error-list-warning ((t (:inherit (highlight warning) :weight normal))))
  '(flycheck-error ((t (:inherit highlight :underline (:color "Red1" :style wave)))))
  '(flycheck-fringe-error ((t (:foreground "#ff2520" :weight normal))))
  '(flycheck-fringe-warning ((t (:inherit warning :weight normal))))
  '(flycheck-fringe-info ((t (:foreground "#b8860b"))))
  '(flycheck-info ((t (:inherit highlight :underline nil))))
  '(flycheck-inline-error ((t (:inherit (highlight error) :underline nil :weight normal))))
  '(flycheck-inline-info ((t (:inherit highlight :foreground "goldenrod1" :underline nil :weight normal))))
  '(flycheck-inline-warning ((t (:inherit (compilation-warning flycheck-inline-error) :underline nil))))
  '(flycheck-posframe-background-face ((t (:inherit default))))
  '(flycheck-posframe-error-face ((t (:inherit flycheck-inline-error))))
  '(flycheck-posframe-info-face ((t (:inherit flycheck-inline-info))))
  '(flycheck-posframe-warning-face ((t (:inherit flycheck-inline-warning))))
  '(flycheck-warning ((t (:inherit highlight))))
  '(flymake-error ((t (:inherit flycheck-error))))
  '(flymake-warning ((t (:inherit font-lock-warning-face))))
  '(font-lock-builtin-face ((t (:foreground "#23ffef" :weight extra-bold))))
  '(font-lock-comment-delimiter-face ((t (:inherit font-lock-comment-face))))
  '(font-lock-comment-face ((t (:foreground "#74af68" :slant italic))))
  '(font-lock-doc-face ((t (:inherit font-lock-string-face :slant italic))))
  '(font-lock-function-name-face ((t (:foreground "#20ca9a" :weight semi-bold))))
  '(font-lock-keyword-face ((t (:foreground "#f68627" :weight bold))))
  '(font-lock-preprocessor-face ((t (:foreground "goldenrod" :slant italic))))
  '(font-lock-regexp-grouping-construct ((t (:inherit bold))))
  '(font-lock-string-face ((t (:foreground "#5bbb35" :weight normal))))
  '(font-lock-type-face ((t (:foreground "#63afd8" :weight semi-bold))))
  '(font-lock-variable-name-face ((t (:foreground "tan"))))
  '(font-lock-warning-face ((t (:inherit (shadow highlight) :underline (:color "lightsalmon3" :style wave)))))
  '(fringe ((t (:background "#373f4a"))))
  '(highlight-operators-face ((t (:foreground "#80e9b3" :weight normal))))
  '(highlight ((t (:inherit nil :background "#2f3f4f"))))
  '(hl-line ((t (:background "#2f3f4f"))))
  '(hl-paren-face ((t (:foreground "#83878e"))) t)
  '(inline-docs-border-face ((t (:inherit default))))
  '(inline-docs-face ((t (:inherit hl-line))))
  '(inline-docs-indicator-face ((t (:inherit default :foreground "#888a8e" :slant italic))))
  '(inline-docs-prefix-face ((t (:inherit cider-result-overlay-face))))
  '(isearch ((t (:foreground "#c9c952" :box (:line-width 1 :color "#757941") :overline nil :underline nil :slant italic :weight bold))))
  '(lazy-highlight ((t (:background "#335f86" :slant italic :weight bold))))
  '(line-number-current-line ((t (:inherit (hl-line line-number)))))
  '(line-number ((t (:inherit (default shadow\  hl-line) :foreground "#8b8682" :slant normal :height 110 :width condensed))))
  '(linum ((t (:inherit (default hl-line) :stipple nil :foreground "#8b8682" :strike-through nil :overline nil :slant normal :height 110 :width condensed))))
  '(lsp-face-highlight-textual ((t (:inherit (semantic-idle-symbol-highlight lazy-highlight)))))
  '(lsp-ui-doc-header ((t (:background "medium purple" :foreground "black"))))
  '(mc/cursor-face ((t (:background "cyan4" :inverse-video nil :box (:line-width 1 :color "#55cc66" :style released-button)))))
  '(mode-line-inactive ((t (:inherit mode-line :background "grey30" :foreground "grey80" :box (:line-width 1 :color "grey40" :style released-button) :overline nil :weight light))))
  '(mode-line ((t (:background "#212931" :foreground "#eeeeec" :box (:line-width 1 :color "#365979" :style released-button) :overline "dark violet"))))
  '(parenthesis ((t (:foreground "#86ab98"))))
  '(region ((t (:inherit hl-line :background "#3d7d5e"))))
  '(scroll-bar ((t nil)))
  '(secondary-selection ((t (:background "SkyBlue4"))))
  '(semantic-unmatched-syntax-face ((t (:underline "#e9967a"))))
  '(semantic-highlight-func-current-tag-face ((t (:background "#414f5a" :underline "#56656f"))))
  '(semantic-idle-symbol-highlight ((t (:underline (:color "#727272" :style wave) :weight bold))))
  '(semantic-tag-boundary-face ((t (:overline "#480068" :underline "#480068"))))
  '(shadow ((t (:foreground "#a3a3a3"))))
  '(show-paren-match ((t (:weight bold :underline (:color "#00efff" :style line) :overline "#00dfff" :box nil :inverse-video nil :foreground "#c3d3e3" :background  "#245281"))))
  '(show-paren-mismatch ((t (:width expanded :weight bold :underline (:color "#ff00ff" :style line) :overline "#ff44ff" :strike-through nil :box nil :foreground "#d9d3d3" :inherit (default)))))
  '(success ((t (:foreground "Green1" :weight normal))))
  '(symbol-overlay-default-face ((t (:background "#364b52"))))
  '(term-bold ((t (:inherit term :weight bold))))
  '(term ((t (:background "#222222" :distant-foreground "#222222"))))
  '(term-underline ((t (:inherit term :underline t))))
  '(trailing-whitespace ((t nil)))
  '(variable-pitch ((t (:family "DejaVu Sans"))))
  '(vertical-border ((((type x tty)) (:inherit mode-line-inactive))))
  '(warning ((t (:foreground "LightSalmon3" :weight normal))))
  '(window-divider-first-pixel ((t (:foreground "dark cyan"))))
  '(window-divider-last-pixel ((t (:foreground "light sea green"))))
  '(window-divider ((t (:foreground "dark cyan"))))
 )

(provide-theme 'local-faces)
